export { default as ProfileTab } from './profile-tab'
export { default as AvatarTab } from './avatar-tab'
export { default as OrdersTab } from './orders-tab'
export { default as AddressesTab } from './addresses-tab'
export { default as ExchangeTab } from './exchange-tab'
export { default as PaymentTab } from './payment-tab'
export { default as SettingsTab } from './settings-tab'
export { default as ProfileHeader } from './profile-header' 